---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- config/
- db/
- spec/
- apps/admin/assets/stylesheets/bootstrap/
- apps/admin/assets/javascripts/jquery.js
- apps/admin/assets/javascripts/jquery_ujs.js
- apps/admin/assets/javascripts/bootstrap.js

