language: ruby
sudo: false
cache: bundler

rvm:
  - 2.2.4
  - 2.3.0

env:
  - DB=sqlite
  - DB=mysql

before_install:
  - cp gemfiles/Gemfile.$DB Gemfile

install: bundle install --jobs=3 --retry=3 --without production

before_script:
  - cp .env.test.$DB .env.test

script:
  - 'HANAMI_ENV=test bundle exec hanami db create'
  - 'HANAMI_ENV=test bundle exec hanami db migrate'
  - 'bundle exec rake test'

