language: ruby

rvm:
  - 2.2.3
  - 2.1.7
  - 2.0.0-p647
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

before_script:
  - "cp config/database.$DB.travis.yml config/database.yml"

  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database firefly_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database firefly_test character set utf8 collate utf8_bin;'; fi"

  - "RACK_ENV=test bundle exec rake db:migrate"

